
development:
    adapter: mysql2
    database: foobar_development
    encoding: utf8
    username: root
    host: localhost
    socket: /opt/boxen/data/mysql/socket

test: &test
  adapter: mysql2
  #adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: foobar_test
  username: root
  socket: /opt/boxen/data/mysql/socket

cucumber:
  <<: *test
